### PR TITLE
Add degen coin flip and degen spin games

### PR DESCRIPTION
**Pull request by SomeAnonDev**
I'm assuming 60x60 is the only size for these images. If there is a better size please let me know.

### CODE REVIEW

**Review by benlvb — APPROVED** [review]

**Comment by benlvb** [comment]
Please solve the conflict, we're ready to merge this @SomeAnonDev

**Comment by SomeAnonDev** [comment]
Rebased and ready to go

**Comment by benlvb** [comment]
Looks good, but just got the info (Will update the readme guideline), is it possible for you to get a better image of 200x200?

**Comment by SomeAnonDev** [comment]
> Looks good, but just got the info (Will update the readme guideline), is it possible for you to get a better image of 200x200?

done

**Review by benlvb — APPROVED** [review]

**Pull request merged**
