### PR TITLE
Adding Cryptorefills

### PR DESCRIPTION
**Pull request by simonlucalandi**
Cryptorefills enables customers to purchase gift cards from top global brands paying with stablecoins over the Solana network.
Since 2019 hundreds of thousands of customers have purchased on Cryptorefills

https://cryptorefills.com

### CODE REVIEW

**Comment by simonlucalandi** [comment]
@0xYankee-Raccoons can you please take a look? Do you need more information to approve the PR?

**Comment by simonlucalandi** [comment]
@0xYankee-Raccoons anything else we can do?

**Comment by 0xYankee-Raccoons** [comment]
Hey @simonlucalandi, can you help us with any of these information?

Screenshot 2024-05-23 at 10 54 36

**Comment by simonlucalandi** [comment]
> Hey @simonlucalandi, can you help us with any of these information?
> 
> Screenshot 2024-05-23 at 10 54 36

@0xYankee-Raccoons here some facts about Cryptorefills

Since 2019 users from 146 countries have purchased giftcards and mobile topups on Cryptorefills.
In Q1 2024 we delivered 50k products to our customers around the world.
We have about 12k followers on twitter https://x.com/cryptorefills 
We have 4.4 stars on TrustPilot https://www.trustpilot.com/review/www.cryptorefills.com 

We have been featured on crypto news websites like:
-  cryptonew.com: https://cryptonews.com/news/payment-use-cases-fuel-increasing-stablecoin-growth.htm
-  Cointelegraph: https://cointelegraph.com/news/cointelegraph-consulting-report-pictures-a-crypto-consumer-portrait
-  Cryptonomist: https://en.cryptonomist.ch/2021/04/15/e-commerce-layer-2-payments-ethereum/

and featured on Payments and Finance media like:
 - https://www.pymnts.com/emea/2022/emea-daily-coinbase-furthers-european-expansion-cryptorefills-adds-euroc-support/
 - https://thepaypers.com/cryptocurrencies/cryptorefills-labs-unveils-stablecoin-shopping-research--1267741
 - https://www.financemagnates.com/thought-leadership/industries-that-are-using-cryptocurrency/

The research data from our labs unit is published on the Statista platform: https://www.statista.com/statistics/1360150/consumer-motivation-on-using-crypto-for-retail/

**Comment by 0xYankee-Raccoons** [comment]
@simonlucalandi, appreciate your patience, the information you've shared is very helpful and will proceed to approve/merge

**Review by 0xYankee-Raccoons — APPROVED** [review]

**Pull request merged**
