### PR TITLE
Adds GooseFx protocol

### PR DESCRIPTION
**Pull request by Shashank729**

### CODE REVIEW

**Review by benlvb — APPROVED** [review]

**Comment by benlvb** [comment]
Screenshot 2024-05-04 at 15 53 44


Apologies, could you put up a better image. @Shashank729 can be another PR.

**Comment by Shashank729** [comment]
Screenshot 2024-05-04 at 1 35 45 PM
Okay @benlvb but the widget is not loading for me, so not sure what image size I should use for the new PR.

**Comment by benlvb** [comment]
Ah yes, will add more clarification and guidelines to the readme. 
For now can you try with a logo with 400x400 (Just the icon) and ideally transparent background?

(There was some formatting issue, it's fixed now, so you should be able to checkout the page)

**Comment by Shashank729** [comment]
Sure thing, let me ask my team for the same. Thank you, it is visible now.

**Comment by Shashank729** [comment]
Hey @benlvb, I've raise another PR to fix the image. Link: https://github.com/jup-ag/welcome-partners/pull/37. Just mentioned here to avoid any confusion.

**Pull request merged**
